Renew page "Funketikette"
taskforcehellcat/wiki pull request #80
Opened 2023-06-01 14:31 UTC by LeonTReal

**Changed:**
- Rewrote some paragraphs
- Added tooltips
- Changed page structure
- Removed unused imports

**TODO before merge:**
- [ ] Proof read
- [ ] Renew NATO alphabet chart? (optional)

2023-06-01 15:42 UTC, pantoffelemmy commented
Can you elaborate on the changes you want to be made to the alphabet chart?

2023-06-01 15:51 UTC, pantoffelemmy requested changes

2023-06-01 15:51 UTC, pantoffelemmy commented on src/content/ausbildung/funketikette.svx
> +„Aufklärung für Truppführung - Information - Infanterie in Gruppenstärke zu Fuß gesichtet nord-west ihrer Aktuellen - Kommen.“
This could use an example box but I understand why we might choose not to use one here.

2023-06-01 15:51 UTC, pantoffelemmy commented on src/content/ausbildung/funketikette.svx
> +Da das NATO-Alphabet auch außerhalb des Funkens viel Anwendung findet, sollte es sich dringend angeeignet werden.
```suggestion
Da das NATO-Alphabet auch außerhalb des Funkens viel Anwendung findet, sollte man es sich dringend aneignen.
```

2023-06-01 17:19 UTC, LeonTReal commented
@pantoffelemmy The current isn't bad as-is and does not **have** to be changed. However, it's quite a huge image white a lot of blank white space, maybe the alphabet could be structured different. Also, it still uses an outdated tfhc logo.

But as I said, it does not need to be changed now. Maybe make this an issue so that we can merge this PR.

2023-06-01 17:23 UTC, pantoffelemmy commented
Oh I see, yes I agree. This will have to wait until I'm back at my PC.

Since this style of info sheet is somewhat outdated as a whole I'd suggest we discuss that separately from this PR.

2023-06-02 11:11 UTC, pantoffelemmy approved these changes

2023-06-02 11:12 UTC, merged