Fliegertruppe
taskforcehellcat/wiki pull request #90
Opened 2023-06-25 12:35 UTC by Der4stronaut

first part for the Fliegertruppe is ready for the wiki. To be more precise the Kampfpilot eines Drehflüglers.

2023-06-26 17:59 UTC, pantoffelemmy requested changes
Hab ein paar Vorschläge zum Ausdruck gemacht. Inhaltlich kann ich dazu nicht so viel sagen wie @LeonTReal.

2023-06-26 17:59 UTC, pantoffelemmy commented on src/content/fliegertruppe/kampfpilot.svx
> +Der Kampfpilot ist verantwortlich für ein komplexes Waffensystem, mit dem Truppenteile durch Kampf aus der Luft unterstützt werden. Er weiß, wie er unter herausfordernden klimatischen Bedingungen und
```suggestion
Der Kampfpilot ist verantwortlich für ein komplexes Waffensystem, mit dem Truppenteile durch Kampf aus der Luft unterstützt werden. Er erfüllt auch unter herausfordernden Bedingungen und in verschiedenem Gelände effektiv und unter Beachtung der Sicherheitsbestimmungen seinen den Auftrag.
```

2023-06-26 17:59 UTC, pantoffelemmy commented on src/content/fliegertruppe/kampfpilot.svx
> +Die Aufgaben des Kampfpiloten eines Drehflüglers besteht in:
```suggestion
Zu den Fertigkeiten und Aufgaben des Kampfpiloten eines Drehflüglers zählen:
```

2023-06-26 17:59 UTC, pantoffelemmy commented on src/content/fliegertruppe/kampfpilot.svx
> +
```suggestion
- die Verantwortung für den zu nutzenden Hubschrauber
- der fliegerische Einsatz des Hubschraubers
- Kenntnisse über den Hubschrauber und seinen Waffenanlagen, sowie die Wirkungsweise der Munition
- die Verantwortung für das unterstellte Personal sowie die sichere Durchführung des Fluges
- Kenntnisse von fliegerischen und taktischen Verfahren
- Kenntnisse im Bereich der Navigation, Aerodynamik, Fluglehre und Luftfahrzeugkunde
- Einschätzung der Durchführbarkeit des Fluges oder Einsatzes in besonderen Lagen
- Führung einer Besatzung auch unter schwierigen Rahmenbedingungen

```

2023-06-26 17:59 UTC, pantoffelemmy commented on src/content/fliegertruppe/kampfpilot.svx
> +Der Kampfpilot sollte in der Lage sein, sich problemlos, unter Beachtung der [Funketikette](/ausbildung/funketikette), zu kommunizieren. Dazu sollte er auch das NATO-Alphabet beherrschen und die Iden
```suggestion
Der Kampfpilot ist in der Lage, problemlos unter Beachtung der [Funketikette](/ausbildung/funketikette) zu kommunizieren. Dazu beherrscht er das NATO-Alphabet und die Identifikation von feindlichen Luftfahrzeugen und Bodenfahrzeugen.
```

2023-07-19 17:56 UTC, LeonTReal approved these changes

2023-07-19 18:04 UTC, merged